# Generated by Django 4.0.7 on 2022-09-06 00:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feed", "0002_alter_post_slug"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="post",
            name="feed_post_status_d0eaa0_idx",
        ),
        migrations.RemoveIndex(
            model_name="post",
            name="feed_post_publish_df921e_idx",
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["id"], name="feed_post_id_970465_idx"),
        ),
    ]
