# Generated by Django 4.0.6 on 2022-07-19 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Title")),
                ("content", models.TextField(verbose_name="content")),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="published",
                        max_length=9,
                    ),
                ),
                ("slug", models.SlugField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-published_at",),
            },
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["status"], name="feed_post_status_d0eaa0_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["published_at"], name="feed_post_publish_df921e_idx"
            ),
        ),
    ]
