# Generated by Django 4.0.7 on 2022-09-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Username"
                    ),
                ),
                ("date_of_birth", models.DateField(verbose_name="Date of birth")),
                ("join_date", models.DateTimeField(auto_now_add=True)),
                (
                    "full_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Full name"
                    ),
                ),
                (
                    "bio",
                    models.TextField(blank=True, max_length=300, verbose_name="Bio"),
                ),
                (
                    "skills",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Your skills"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="Phone Number"
                    ),
                ),
                (
                    "github",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Github username"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
