# Generated by Django 4.0.7 on 2022-09-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_bio_alter_user_skills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Full name"
            ),
        ),
    ]
