# Generated by Django 4.0.7 on 2022-09-13 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_user_full_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, max_length=500, verbose_name="Bio"),
        ),
        migrations.AlterField(
            model_name="user",
            name="github",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Github username"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="skills",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Your skills."
            ),
        ),
    ]
